### ISSUE TITLE
parsha is wrong 

### ISSUE THREAD

**Issue by yskraus** [zmanim/zman#11] opened 2019-10-07 17:09 UTC
todays date is showing the parish as וילך 
and its האזינו

**Comment by yskraus** [comment] 2019-10-07 18:31
I think on zman/zman/src/Getters/Parsha.php:129
instead of             if ($count < 2) {
should be             if ($count == 2) {

**Comment by zachweix** [comment] 2019-10-07 18:32
I'm looking at the code that calculates the Parshios and I see that it looks like the issue is in "src/Getters/Parsha.php" between lines 129 and 135. Right now if there is only one Shabbos, it will always be Haazinu and if there are two it looks like before Yom Kippur (of the following year, i.e. always) will be Vayelech, otherwise Haazinu

**Comment by zachweix** [comment] 2019-10-07 18:33
I'm working on a merge request right now, because I also noticed that the week of Pesach this year was incorrect as well

**Comment by yskraus** [comment] 2019-10-07 18:34
> I think on zman/zman/src/Getters/Parsha.php:129
> instead of if ($count < 2) {
> should be if ($count == 2) {

this is wrong

**Comment by tam5** [comment] 2019-10-07 18:34
thanks, happy to merge when you have a fix

**Comment by zachweix** [comment] 2019-10-07 18:36
It needs to be as follows:
if count < 2 (only one Shabbos of leining between RH and Sukkos)
    if before Shabbos Shuva, Haazinu
    else V'zos Habracha
else
    if before Shabbos Shuva, Vayelech
    else if before Shabbos between YK and Sukkos, Haazinu
     else, Vzos Habracha

**Comment by zachweix** [comment] 2019-10-07 19:24
I believe I have taken care of this issue in Pull Request #12 
I fixed the area around Rosh Hashana, so it should be showing the correct Parsha now, as well as an issue that showed up around Pesach of this year where it was showing the wrong Parsha in America

**Comment by tam5** [comment] 2019-10-07 23:44
fixed by @zachweix with #12

**Closed by tam5** 2019-10-07 23:44 UTC
Labels: Status: Complete, Type: Bug

**Comment by yskraus** [comment] 2020-09-14 03:11
This issue is back
